export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Game & Room errors
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_FULL = 'ROOM_FULL',
  GAME_ALREADY_STARTED = 'GAME_ALREADY_STARTED',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  INVALID_PHASE = 'INVALID_PHASE',
  CARD_NOT_IN_HAND = 'CARD_NOT_IN_HAND',
  EMPTY_DISCARD_PILE = 'EMPTY_DISCARD_PILE',
  ACTION_IN_FLIGHT = 'ACTION_IN_FLIGHT',
  INVALID_DECLARATION = 'INVALID_DECLARATION',
  PLAYER_NOT_IN_ROOM = 'PLAYER_NOT_IN_ROOM',
  DISCONNECTED_TIMEOUT = 'DISCONNECTED_TIMEOUT'
}

export interface AppErrorPayload {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
